parent=keycloak.v3
import=common/keycloak

# Giao diện Cổng Quản lý Tài khoản Amigo Enterprise
styles=css/account.css?v=20260916-2
scripts=js/account-custom.js?v=20260916-2
locales=vi,en

title=Amigo - Cổng quản lý tài khoản
logo=img/amigo-logo-transparent.png
logoUrl=.
darkMode=false
