apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: amigo-keycloak
  namespace: ssc3
spec:
  instances: 2
  image: quay.ocp.lab.local/dinhhb/keycloak-custom:1.0.0
  startOptimized: true
  update:
    strategy: Auto

  db:
    vendor: postgres
    host: postgresql.ssc3.svc
    database: keycloak
    usernameSecret:
      name: keycloak-db
      key: username
    passwordSecret:
      name: keycloak-db
      key: password

  hostname:
    hostname: keycloak.apps.example.com

  http:
    tlsSecret: keycloak-tls

  additionalOptions:
    - name: metrics-enabled
      value: "true"

  resources:
    requests:
      cpu: 500m
      memory: 768Mi
    limits:
      cpu: "2"
      memory: 2Gi

  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
